/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System Health & Liveness Probe
         * @description Check status and latency of core infrastructure dependencies (database, cache, storage).
         */
        get: operations["v1.health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["v1.auth.register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate a user and issue API token */
        post: operations["v1.auth.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send password reset link to email */
        post: operations["v1.auth.forgot-password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset password using token */
        post: operations["v1.auth.reset-password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke current access token */
        post: operations["v1.auth.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke all access tokens across all devices */
        post: operations["v1.auth.logout-all"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get authenticated user profile */
        get: operations["v1.auth.me"];
        /** Update authenticated user profile */
        put: operations["v1.auth.update-me"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change user password */
        post: operations["v1.auth.change-password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/media/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Local storage signed upload handler for development environments */
        put: operations["v1.media.upload"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/signed-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a pre-signed URL for direct binary upload to cloud or local storage */
        post: operations["v1.signed-url"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Display a listing of users with dynamic filters, sorting, sparse fieldsets, and pagination */
        get: operations["v1.users.index"];
        put?: never;
        /** Store a newly created user in storage */
        post: operations["v1.users.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{user}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Display the specified user by ID */
        get: operations["v1.users.show"];
        /** Update the specified user in storage */
        put: operations["v1.users.update"];
        post?: never;
        /** Remove the specified user from storage */
        delete: operations["v1.users.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthResource */
        AuthResource: {
            user: components["schemas"]["UserResource"];
            token: string;
            /** @constant */
            token_type: "Bearer";
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            current_password: string;
            password: string;
            password_confirmation: string;
        };
        /** ForgotPasswordRequest */
        ForgotPasswordRequest: {
            /** Format: email */
            email: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
            device_name?: string | null;
        };
        /** Media */
        Media: {
            id: number;
            disk: string;
            directory: string;
            filename: string;
            extension: string | null;
            mime_type: string | null;
            aggregate_type: string;
            size: number;
            url: string;
            created_at: string | null;
            updated_at: string | null;
        };
        /** PersonalAccessTokenResource */
        PersonalAccessTokenResource: {
            id: number;
            tokenable_type: string;
            tokenable_id: number;
            name: string;
            abilities: unknown[] | null;
            /** Format: date-time */
            last_used_at: string | null;
            /** Format: date-time */
            expires_at: string | null;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
        };
        /** RegisterRequest */
        RegisterRequest: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
            device_name?: string | null;
            password_confirmation: string;
        };
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            token: string;
            /** Format: email */
            email: string;
            password: string;
            password_confirmation: string;
        };
        /** SignedUrlRequest */
        SignedUrlRequest: {
            filename: string;
            /** @enum {string} */
            tag: "profile" | "avatar" | "banner" | "thumbnail" | "document" | "attachment" | "chat" | "default";
        };
        /** StoreRequest */
        StoreRequest: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
            profile?: {
                filename?: string;
                directory?: string;
                size?: number;
                /** @enum {string} */
                mime_type?: "image/jpeg" | "image/png" | "image/gif" | "image/webp" | "image/svg+xml" | "image/x-icon";
            };
        };
        /** UpdateProfileRequest */
        UpdateProfileRequest: {
            name?: string;
            /** Format: email */
            email?: string;
        };
        /** UpdateRequest */
        UpdateRequest: {
            name?: string;
            /** Format: email */
            email?: string;
            password?: string | null;
            profile?: {
                filename?: string;
                directory?: string;
                size?: number;
                /** @enum {string} */
                mime_type?: "image/jpeg" | "image/png" | "image/gif" | "image/webp" | "image/svg+xml" | "image/x-icon";
            };
        };
        /** UserResource */
        UserResource: {
            id: number;
            name: string;
            email: string;
            /** Format: date-time */
            email_verified_at: string | null;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
            is_verified: string;
            profile?: components["schemas"]["Media"] | null;
            tokens?: components["schemas"]["PersonalAccessTokenResource"][];
        };
    };
    responses: {
        /** @description Validation error */
        ValidationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Errors overview. */
                    message: string;
                    /** @description A detailed description of each field that failed validation. */
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
        /** @description Unauthenticated */
        AuthenticationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Not found */
        ModelNotFoundException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "v1.health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    "v1.auth.register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @constant */
                        message: "User registered successfully.";
                        data: components["schemas"]["AuthResource"];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "v1.auth.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @constant */
                        message: "Logged in successfully.";
                        data: components["schemas"]["AuthResource"];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "v1.auth.forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        data: null;
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        errors: null;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "v1.auth.reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        data: null;
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        errors: null;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "v1.auth.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @constant */
                        message: "Logged out successfully.";
                        data: null;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "v1.auth.logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @constant */
                        message: "Logged out from all devices successfully.";
                        data: null;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "v1.auth.me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @constant */
                        message: "User profile retrieved successfully.";
                        data: components["schemas"]["UserResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "v1.auth.update-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @constant */
                        message: "Profile updated successfully.";
                        data: components["schemas"]["UserResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "v1.auth.change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @constant */
                        message: "Password changed successfully.";
                        data: null;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "v1.media.upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @constant */
                        message: "File uploaded successfully to local storage.";
                        data: {
                            disk: string;
                            key: string;
                            size: number;
                        };
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @constant */
                        message: "Invalid storage key provided.";
                        errors: null;
                    };
                };
            };
        };
    };
    "v1.signed-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignedUrlRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @constant */
                        message: "Pre-signed upload URL generated successfully.";
                        data: {
                            url: string;
                            file_url: string;
                            key: string;
                            directory: string;
                            filename: string;
                            extension: string;
                            mime_type: string;
                            tag: string;
                            disk: string;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "v1.users.index": {
        parameters: {
            query?: {
                /** @description Multi-column search across string fields (e.g. name, email). */
                search?: string;
                /** @description Filter records by name. */
                "filter[name]"?: string;
                /** @description Filter records by email. */
                "filter[email]"?: string;
                /** @description Filter records created on or after date (YYYY-MM-DD). */
                "filter[created_at_after]"?: string;
                /** @description Filter records created on or before date (YYYY-MM-DD). */
                "filter[created_at_before]"?: string;
                /** @description Sort by column(s). Prefix with - for descending order. Available: id, name, email, created_at, updated_at. Example: -id,id, -name,name, -email,email */
                sort?: string;
                /** @description Comma-separated sparse fieldsets to select on the root model (e.g. id,name,email). */
                fields?: string;
                /** @description Comma-separated relationships to eager load without N+1. Available: tokens, media */
                include?: string;
                /** @description Comma-separated media tags to eager-load in resource responses. Available: profile, avatar, banner, thumbnail, document, attachment, chat, default */
                media?: string;
                /** @description Comma-separated sparse fieldsets for the 'tokens' relationship. */
                "fields[tokens]"?: string;
                /** @description Comma-separated sparse fieldsets for the 'media' relationship. */
                "fields[media]"?: string;
                /** @description Comma-separated computed accessors to append dynamically. Available: is_verified, initials, latest_token_name, avatar_url */
                append?: string;
                /** @description Number of items per page (1-100). Default: 15. */
                per_page?: number;
                /** @description Set to -1 to retrieve all matching records in a single unpaginated response. */
                limit?: number;
                /** @description Page number for standard LengthAware pagination. */
                page?: number;
                /** @description Cursor token for high-scale cursor pagination. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @constant */
                        message: "Users retrieved successfully.";
                        data: string;
                        meta: {
                            pagination: {
                                per_page: number;
                                count: number;
                                has_more_pages: boolean;
                                total: number;
                                current_page: number;
                                total_pages: number;
                                from: number | null;
                                to: number | null;
                                next_page_url: string | null;
                                prev_page_url: string | null;
                                next_cursor: string | null;
                                prev_cursor: string | null;
                            };
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "v1.users.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @constant */
                        message: "User created successfully.";
                        data: components["schemas"]["UserResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "v1.users.show": {
        parameters: {
            query?: {
                /** @description Comma-separated sparse fieldset columns to select on the model. */
                fields?: string;
                /** @description Comma-separated relationships to eager load. Available: tokens, media */
                include?: string;
                /** @description Comma-separated media tags to eager-load in resource responses. Available: profile, avatar, banner, thumbnail, document, attachment, chat, default */
                media?: string;
                /** @description Comma-separated sparse fieldsets for the 'tokens' relationship. */
                "fields[tokens]"?: string;
                /** @description Comma-separated sparse fieldsets for the 'media' relationship. */
                "fields[media]"?: string;
                /** @description Comma-separated computed accessors to append dynamically. Available: is_verified, initials, latest_token_name, avatar_url */
                append?: string;
            };
            header?: never;
            path: {
                /** @description The user ID */
                user: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @constant */
                        message: "User retrieved successfully.";
                        data: components["schemas"]["UserResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "v1.users.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user ID */
                user: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @constant */
                        message: "User updated successfully.";
                        data: components["schemas"]["UserResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "v1.users.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user ID */
                user: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @constant */
                        message: "User deleted successfully.";
                        data: null;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
}
